name: ukraine-energy-future
channels:
    - conda-forge
    - bioconda
    - gurobi
dependencies:
    - python=3.10
    - flake8=3.8.3
    - snakemake-minimal=7.22.0

    # all the following are pypsa-eur dependencies
    - pypsa=0.23.0
    - atlite>=0.2.9
    - dask
    - jupyter
    - nbconvert

      # Dependencies of the workflow itself
    - xlrd
    - openpyxl!=3.1.1
    - pycountry
    - seaborn
    - snakemake-minimal
    - memory_profiler
    - yaml
    - pytables
    - lxml
    - powerplantmatching>=0.5.5
    - numpy<1.24
    - pandas>=1.4
    - geopandas>=0.11.0
    - xarray=2023.2.0
    - libnetcdf=4.9.1
    - netcdf4=1.6.3
    - networkx
    - scipy
    - shapely>=2.0
    - pyomo
    - matplotlib<3.6
    - proj
    - fiona
    - country_converter

      # Keep in conda environment when calling ipython
    - ipython

    # GIS dependencies:
    - cartopy
    - descartes
    - rasterio!=1.2.10

    # PyPSA-Eur-Sec Dependencies
    - geopy
    - tqdm
    - pytz
    - tabula-py
    - pyxlsb

    - gurobi=10.0.1

    - pip
    - pip:
        - vresutils>=0.3.1
        - tsam>=1.1.0
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
