slurm: True # TODO add resource use to logs
jobs: 999
local-cores: 1
cores: 10
latency-wait: 60
use-envmodules: True
use-conda: True
conda-frontend: mamba
conda-prefix: ../envs/snakemake/ukraine-energy-future
configfile: config/full.yaml
max-jobs-per-second: 10
max-status-checks-per-second: 1
default-resources:
    - runtime=10
    - mem_mb_per_cpu=4000
    - mem_mb=4000
    - slurm_account=es_apatt # TODO keep out of repository
