cluster: bsub -oo build/logs/{rule}.{wildcards}.log -W {resources.runtime} -n {threads} -R "rusage[mem={resources.memory}]" -J {rule}.{wildcards} <
jobs: 999
local-cores: 1
cores: 10
latency-wait: 60
use-envmodules: True
use-conda: True
conda-frontend: mamba
conda-prefix: ../envs/snakemake/ukraine-energy-future
default-resources: [
    "runtime=10",
    "memory=16000"
]
