# The right place for all your configuration values.
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/ukraine-energy-future
    local-results-dir: build/cluster
resolution:
    space: 6 # number of nodes in the model
    time: 24H
pypsa-eur:
    biomass:
        potential: 513000000 # [@Geletukha:2020]
        FOM: 4.1 # from Euro-Calliope
        VOM: 3.1 # from Euro-Calliope
        fuel: 18.47 # from Euro-Calliope
        investment: 2300 # from Euro-Calliope
        lifetime: 20 # from Euro-Calliope
        efficiency: 0.45 # from Euro-Calliope
        "discount rate": 0.1 # also defined in `costs`, [@Andersson:2020]
    costs:
        "discount rate": 0.1 # also defined in `biomass`, [@Andersson:2020]
    run:
        shared_cutouts: true
    scenario:
        simpl: ['']
        ll: [vopt]
        clusters: [6]
        opts: [24H]

    countries:
        - UA

    electricity:
        renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
        estimate_renewable_capacities:
            enable: false
        BAU_mincapacities:
            biomass: 0
            solar: 0
            onwind: 0
            offwind-ac: 0
            offwind-dc: 0

    renewable:
        solar:
            cutout: europe-2013-era5

    conventional:
        nuclear:
            p_max_pu: 1 # TODO update

    solving:
        options:
            load_shedding: true
        solver:
            options: gurobi-numeric-focus
scenarios:
    nuclear-and-renewables-low:
        run:
            name: "nuclear-and-renewables-low"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 24500 # to reach pre-war electricity share (~55%)
    only-renewables-low:
        run:
            name: "only-renewables-low"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass]
    nuclear-and-renewables-high:
        run:
            name: "nuclear-and-renewables-high"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 52000 # to reach pre-war electricity share (~55%)
    only-renewables-high:
        run:
            name: "only-renewables-high"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass]
global-sensitivity-analysis:
    resolution:
        space: 2
        time: 168H
    parameters:
        nuclear+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        solar+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        onwind+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        biomass+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        H2+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        battery+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        nuclear+m:
            min: 0.25 # TODO update
            max: 2 # TODO update
        biomass+m:
            min: 0.25 # TODO update
            max: 2 # TODO update
        biomassstore+e:
            min: 0.25 # TODO update
            max: 2 # TODO update
    seed: 5839
    number-trajectories: 5
report:
    nice-names:
        technology:
            biomass: "Biomass"
            nuclear: "Nuclear"
            onwind: "Wind"
            solar: "Solar"
            hydro: "Hydro"
            "battery charger": "Battery charger"
            "battery discharger": "Battery discharger"
            PHS: "Pumped hydro"
            fossil: "Fossil"
    scenario-sets:
        main:
            - pre-war
            - nuclear-and-renewables-high
            - only-renewables-high
        all:
            - pre-war
            - nuclear-and-renewables-low
            - nuclear-and-renewables-high
            - only-renewables-low
            - only-renewables-high
    scenario-colors:
        pre-war: "#424242"
        nuclear-and-renewables-low: "#FCDC98"
        nuclear-and-renewables-high: "#FABC3C"
        only-renewables-low: "#A0CB71"
        only-renewables-high: "#679436"
    pre-war:
        capacities:
            nuclear: 13.9 # https://en.wikipedia.org/wiki/Nuclear_power_in_Ukraine
            solar: 8.1 # IRENA
            hydro: 6.6 # IRENA
            onwind: 1.7 # IRENA
            biomass: 0.3 # IRENA
            fossil: 21.5 # TODO add Olena's source
        electricity-mix: # 2021 https://ourworldindata.org/energy/country/ukraine
            nuclear: 0.55
            solar: 0.04
            hydro: 0.07
            onwind: 0.03
            biomass: 0.005
            fossil: 0.30
