# The right place for all your configuration values.
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/ukraine-energy-future
    local-results-dir: build/cluster
resolution:
    space: 6 # number of nodes in the model
    time: 24H
pypsa-eur:
    biomass:
        potential: 513000000 # [@Geletukha:2020]
        FOM: 4.1 # from Euro-Calliope
        VOM: 3.1 # from Euro-Calliope
        fuel: 18.47 # from Euro-Calliope
        investment: 2300 # from Euro-Calliope
        lifetime: 20 # from Euro-Calliope
        efficiency: 0.45 # from Euro-Calliope
        "discount rate": 0.1 # also defined in `costs`, [@Andersson:2020]
    costs:
        "discount rate": 0.1 # also defined in `biomass`, [@Andersson:2020]
    run:
        shared_cutouts: true
    scenario:
        simpl: ['']
        ll: [vopt]
        clusters: [6]
        opts: [24H]

    countries:
        - UA

    enable:
        build_cutout: true
        retrieve_cutout: false

    snapshots:
        start: "2013-01-01"
        end: "2016-01-01"

    atlite:
        cutouts:
            europe-2013-2015-era5:
                module: era5
                x: [20., 42.]
                y: [42., 53.]
                time: ['2013', '2015']

    electricity:
        renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
        estimate_renewable_capacities:
            enable: false
        BAU_mincapacities:
            biomass: 0
            solar: 0
            onwind: 0
            offwind-ac: 0
            offwind-dc: 0

    renewable:
        solar:
            cutout: europe-2013-2015-era5
        onwind:
            cutout: europe-2013-2015-era5
        offwind-ac:
            cutout: europe-2013-2015-era5
        offwind-dc:
            cutout: europe-2013-2015-era5
        hydro:
            cutout: europe-2013-2015-era5

    conventional:
        nuclear:
            p_max_pu: 1 # TODO update

    solving:
        options:
            load_shedding: true
        solver:
            options: gurobi-numeric-focus
scenarios:
    nuclear-and-renewables:
        run:
            name: "nuclear-and-renewables"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 60000 # TODO update to pre-war share (~50%)
    only-renewables:
        run:
            name: "only-renewables"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass]
global-sensitivity-analysis:
    parameters: # TODO biomass-potential if possible
        nuclear+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        solar+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        onwind+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        biomass+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        H2+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        battery+c:
            min: 0.25 # TODO update
            max: 2 # TODO update
        nuclear+m:
            min: 0.25 # TODO update
            max: 2 # TODO update
        biomass+m:
            min: 0.25 # TODO update
            max: 2 # TODO update
    seed: 5839
    number-trajectories: 15
