# The right place for all your configuration values.
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/ukraine-energy-future
    local-results-dir: build/cluster
push:
    from: build/cluster
    logs: build/logs
    to: ~/Documents/work/projects/ukraine-energy-future
resolution:
    space: 6 # number of nodes in the model
    time: 24H
pypsa-eur:
    biomass:
        potential: 1026000000 # [@Geletukha:2020] 513000000 times number of years
        FOM: 4.1 # from Euro-Calliope
        VOM: 3.1 # from Euro-Calliope
        fuel: 18.47 # from Euro-Calliope
        investment: 2300 # from Euro-Calliope
        lifetime: 20 # from Euro-Calliope
        efficiency: 0.45 # from Euro-Calliope
        "discount rate": 0.122 # also defined in `costs`, [@IRENA:2023]
    costs:
        "discount rate": 0.122 # also defined in `biomass`, [@IRENA:2023]
    run:
        shared_cutouts: true
    scenario:
        simpl: ['']
        ll: [vopt]
        clusters: [6]
        opts: [24H]

    countries:
        - UA

    enable:
        build_cutout: true
        retrieve_cutout: false

    snapshots: # any change in total duration requires change of biomass potential above
        start: "2010-01-01"
        end: "2012-01-01"

    atlite:
        cutouts:
            europe-2010-2014-era5:
                module: era5
                x: [20., 42.]
                y: [42., 53.]
                time: ['2010', '2014']

    electricity:
        renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
        estimate_renewable_capacities:
            enable: false
        BAU_mincapacities:
            biomass: 0
            biomassinflow: 0
            solar: 0
            onwind: 0
            offwind-ac: 0
            offwind-dc: 0

    renewable:
        solar:
            cutout: europe-2010-2014-era5
        onwind:
            cutout: europe-2010-2014-era5
        offwind-ac:
            cutout: europe-2010-2014-era5
        offwind-dc:
            cutout: europe-2010-2014-era5
        hydro:
            cutout: europe-2010-2014-era5

    conventional:
        nuclear:
            p_max_pu: 1 # TODO update

    solving:
        options:
            load_shedding: false
        solver:
            options: gurobi-numeric-focus
scenarios:
    nuclear-and-renewables-low:
        run:
            name: "nuclear-and-renewables-low"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 24500 # to reach pre-war electricity share (~55%)
    only-renewables-low:
        run:
            name: "only-renewables-low"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass]
    nuclear-and-renewables-high:
        run:
            name: "nuclear-and-renewables-high"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 52000 # to reach pre-war electricity share (~55%)
    only-renewables-high:
        run:
            name: "only-renewables-high"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass]
    only-renewables-scaled:
        run:
            name: "only-renewables-scaled"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass]
    nuclear-and-renewables-today:
        run:
            name: "nuclear-and-renewables-today"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, offwind-ac, offwind-dc, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 13900 # https://en.wikipedia.org/wiki/Nuclear_power_in_Ukraine
global-sensitivity-analysis:
    resolution:
        space: 2
        time: 168H
    parameters:
        nuclear+c:
            min: 0.25
            max: 2
        solar+c:
            min: 0.25
            max: 2
        onwind+c:
            min: 0.25
            max: 2
        offwind+c:
            min: 0.25
            max: 2
        biomass+c:
            min: 0.25
            max: 2
        H2+c:
            min: 0.25
            max: 2
        battery+c:
            min: 0.25
            max: 2
        nuclear+m:
            min: 0.25
            max: 2
        biomass+m:
            min: 0.25
            max: 2
        biomassinflow+l:
            min: 0.25
            max: 2
    seed: 5839
    number-trajectories: 5
report:
    nice-names:
        technology:
            biomass: "Biomass"
            nuclear: "Nuclear"
            onwind: "Onshore wind"
            offwind: "Offshore wind"
            solar: "Solar"
            hydro: "Hydro"
            "battery charger": "Battery charger"
            "battery discharger": "Battery discharger"
            "H2 electrolysis": "H2 electrolysis"
            "H2 fuel cell": "H2 fuel cell"
            PHS: "Pumped hydro"
            fossil: "Fossil"
            average-load: "Average demand"
            H2: Hydrogen
            battery: Battery
            biomassstore: Biomass
        component:
            biomass: Biomass
            nuclear: Nuclear
            grid: Grid
            renewable: "Wind, water, sun"
            storage: "Storage"
        scenario:
            nuclear-and-renewables-high: nuclear-and-renewables
            only-renewables-high: only-renewables
            nuclear-and-renewables-low: nuclear-and-renewables-low-demand
            only-renewables-low: only-renewables-low-demand
            pre-war: pre-war
    scenario-sets:
        main:
            - pre-war
            - nuclear-and-renewables-high
            - only-renewables-high
        all:
            - pre-war
            - nuclear-and-renewables-low
            - nuclear-and-renewables-high
            - only-renewables-low
            - only-renewables-high
    scenario-colors:
        pre-war: "#424242"
        nuclear-and-renewables-low: "#FCDC98"
        nuclear-and-renewables-high: "#FABC3C"
        nuclear-and-renewables-today: "#EEFA3C"
        only-renewables-low: "#A0CB71"
        only-renewables-high: "#679436"
        only-renewables-scaled: "#BFE90D"
    components:
        mapping:
            "Battery Storage": Storage
            "Hydrogen Storage": Storage
            "biomassstore": Biomass
            "Pumped Hydro Storage": Storage
            "Reservoir & Dam": "Wind, water, sun"
            "Biomass": Biomass
            "H2 electrolysis": Storage
            "H2 fuel cell": Storage
            "battery charger": Storage
            "battery discharger": Storage
            "Nuclear": Nuclear
            "Offshore Wind (AC)": "Wind, water, sun"
            "Offshore Wind (DC)": "Wind, water, sun"
            "Onshore Wind": "Wind, water, sun"
            "Solar": "Wind, water, sun"
            "biomassinflow": Biomass
            "AC": Grid
        colors:
            Nuclear: "#A01914"
            Storage: "#72B7B1"
            Grid: "#F58418"
            "Wind, water, sun": "#FABC3C"
            Biomass: "#679436"
    pre-war:
        capacities:
            nuclear: 13.9 # https://en.wikipedia.org/wiki/Nuclear_power_in_Ukraine
            solar: 8.1 # IRENA
            hydro: 6.6 # IRENA
            onwind: 1.7 # IRENA
            offwind: 0 # IRENA
            biomass: 0.3 # IRENA
            fossil: 21.5 # TODO add Olena's source
            average-load: 17.5 # own calculation using DESSTINEE
        electricity-mix: # 2021 https://ourworldindata.org/energy/country/ukraine
            nuclear: 0.55
            solar: 0.04
            hydro: 0.07
            onwind: 0.03
            offwind: 0
            biomass: 0.005
            fossil: 0.30
    global-sensitivity-analysis:
        zero-line: 1000
