# The right place for all your configuration values.
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/ukraine-energy-future
    local-results-dir: build/cluster
scenarios:
    nuclear-and-renewables:
        run:
            name: "nuclear-and-renewables"
            shared_cutouts: true
        scenario:
            simpl: ['']
            ll: [vopt]
            clusters: [6]
            opts: [24H]

        countries:
            - UA

        electricity:
            conventional_carriers: [biomass, coal] # FIXME replace coal with nuclear
            extendable_carriers:
                Generator: [solar, onwind, biomass]
            renewable_carriers: [solar, onwind, hydro]
            estimate_renewable_capacities:
                enable: false

        renewable:
            solar:
                cutout: europe-2013-era5

        conventional:
            nuclear:
                p_max_pu: pypsa-eur/data/nuclear_p_max_pu.csv

        solving:
            options:
                load_shedding: true
            solver:
                options: gurobi-numeric-focus
    only-renewables:
        run:
            name: "only-renewables"
            shared_cutouts: true
        scenario:
            simpl: ['']
            ll: [vopt]
            clusters: [6]
            opts: [24H]

        countries:
            - UA

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, biomass]
            renewable_carriers: [solar, onwind, hydro]
            estimate_renewable_capacities:
                enable: false

        renewable:
            solar:
                cutout: europe-2013-era5

        conventional:
            nuclear:
                p_max_pu: pypsa-eur/data/nuclear_p_max_pu.csv

        solving:
            options:
                load_shedding: true
            solver:
                options: gurobi-numeric-focus
