# The right place for all your configuration values.
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/ukraine-energy-future
    local-results-dir: build/cluster
pypsa-eur:
    biomass:
        potential: 172000000 # TODO add source
        FOM: 4.1 # from Euro-Calliope
        VOM: 3.1 # from Euro-Calliope
        fuel: 18.47 # from Euro-Calliope
        investment: 2300 # from Euro-Calliope
        lifetime: 20 # from Euro-Calliope
        efficiency: 0.45 # from Euro-Calliope
        "discount rate": 0.1 # also defined in `costs`, [@Andersson:2020]
    costs:
        "discount rate": 0.1 # also defined in `biomass`, [@Andersson:2020]
    run:
        shared_cutouts: true
    scenario:
        simpl: ['']
        ll: [vopt]
        clusters: [6]
        opts: [24H]

    countries:
        - UA

    electricity:
        renewable_carriers: [solar, onwind, hydro]
        estimate_renewable_capacities:
            enable: false

    renewable:
        solar:
            cutout: europe-2013-era5

    conventional:
        nuclear:
            p_max_pu: 1 # TODO update

    solving:
        options:
            load_shedding: true
        solver:
            options: gurobi-numeric-focus
scenarios:
    nuclear-and-renewables:
        run:
            name: "nuclear-and-renewables"

        electricity:
            conventional_carriers: [biomass, nuclear]
            extendable_carriers:
                Generator: [solar, onwind, biomass, nuclear]
            BAU_mincapacities:
                nuclear: 60000 # TODO update to pre-war share (~50%)
                biomass: 0
                solar: 0
                onwind: 0
    only-renewables:
        run:
            name: "only-renewables"

        electricity:
            conventional_carriers: [biomass]
            extendable_carriers:
                Generator: [solar, onwind, biomass]
