resolution:
    space: 6 # number of nodes in the model
    time: 1H
global-sensitivity-analysis:
    resolution:
        space: 6
        time: 1H
    number-trajectories: 15
pypsa-eur:
    biomass:
        potential: 2565000000 # [@Geletukha:2020] 513000000 times number of years
    snapshots: # any change in total duration requires change of biomass potential above
        start: "2010-01-01"
        end: "2015-01-01"
